accounts/urls.py
from django.urls import path, include

from . import views

app_name = 'accounts'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    #Registration page
    path('register/', views.register, name='register'),
]

budget/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('playground/', include('playground.urls')),
    path ('accounts/', include('accounts.urls')),
    path ('', include('tracker.urls')),
    
]

tracker/urls.py
from django.urls import path

from . import views

app_name = 'tracker'
urlpatterns = [
    #Home page
    path('', views.index, name='index'),
    #transactions page
    path('transactions/', views.transactions, name='transactions'),
    #transaction detail page
    path('transactions/<int:transaction_id>/', views.transaction, name='transaction'),
    #Adding new transactions
    path('add_transaction/', views.add_transaction, name='add_transaction'),
    #delete trnsaction
    path('delete_transaction/<int:transaction_id>/', views.delete_transaction, name='delete_transaction'),
    #delete imcome
    path('delete_income/<int:income_id>/', views.delete_income, name='delete_income'),
    #Edit transaction
    path('edit_transaction/<int:transaction_id>/', views.edit_transaction, name='edit_transaction'),
    #Edit income
    path('edit_income/<int:income_id>/', views.edit_income, name='edit_income'),
    #incomes page
    path('incomes/', views.incomes, name='incomes'),
    #adding income
    path('add_income/', views.add_income, name='add_income'),

]

tracker/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

class Transaction(models.Model):
    CATEGORY_GROCERIES = 'GR'
    CATEGORY_UTILITIES = 'UT'
    CATEGORY_ENTERTAINMENT = 'EN'
    CATEGORY_OTHER = 'OT'
    CATEGORY_CAR = 'CR'
    CATEGORY_SUBSCRIPTION = 'SB'

    CATEGORY_CHOICES = [
        (CATEGORY_GROCERIES, 'Groceries'),
        (CATEGORY_UTILITIES, 'Utilities'),
        (CATEGORY_ENTERTAINMENT, 'Entertainment'),
        (CATEGORY_OTHER, 'Other'),
        (CATEGORY_CAR, 'Car'),
        (CATEGORY_SUBSCRIPTION, 'Subscription'),
    ]
    slug = models.SlugField()
    store = models.CharField(max_length=100)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField(auto_now=True)
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES, default=CATEGORY_OTHER)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return f"{self.store} - {self.amount} on {self.date}"
    
    def clean(self):
        if self.amount < 0:
            raise ValidationError('Amount must be non-negative.')

    
    

    
    
class Income(models.Model):
    source = models.CharField(max_length=100)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return f"{self.source} - {self.amount}"
    
    def clean(self):
        if self.amount < 0:
            raise ValidationError('Amount must be non-negative.')

tracker/forms.py
from django import forms

from .models import Transaction, Income

class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['store', 'amount','category']
        labels = {
            'store': 'Store Name',
            'amount': 'Amount Spent',
            'category': 'Category',
        }

class IncomeForm(forms.ModelForm):
    class Meta:
        model = Income
        fields = ['source', 'amount']
        labels = {
            'source': 'Source of income',
            'amount': 'Income amount'
        }

tracker/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Sum
from django.db.models.functions import TruncMonth
from django.contrib.auth.decorators import login_required
from tracker.filters import TransactionFilter
import json
import calendar



from .models import Transaction, Income
from .forms import TransactionForm, IncomeForm

# Create your views here.
def index(request):
    return render(request, 'tracker/index.html')

@login_required
def transactions(request):
    base_qs = Transaction.objects.filter(
        owner=request.user
    ).order_by('-date')

    transactions_filter = TransactionFilter(
        request.GET,
        queryset=base_qs
    )

    filtered_qs = transactions_filter.qs

    total_spent_filtered = filtered_qs.aggregate(
        Sum('amount')
    )['amount__sum'] or 0

    total_spent_all = base_qs.aggregate(
        Sum('amount')
    )['amount__sum'] or 0

    income = Income.objects.filter(owner=request.user).first()
    income_amount = income.amount if income else 0
    balance = income_amount - total_spent_all

    # Prepare data for Chart.js
    data = (
        filtered_qs
        .annotate(month=TruncMonth('date'))
        .values('month','date')
        .annotate(total=Sum('amount'))
        .order_by('month')
    )

    chart_labels = [entry['month'].strftime('%Y-%m') for entry in data]
    chart_totals = [float(entry['total']) for entry in data]

    slected_month = transactions_filter.data.get('month')
    selected_year = transactions_filter.data.get('year')

    month_name = calendar.month_name[int(slected_month)] if slected_month else 'All Months'

    context = {
        'filter': transactions_filter,
        'transactions': filtered_qs,
        'total_spent_filtered': total_spent_filtered,
        'total_spent_all': total_spent_all,
        'balance': balance,
        'chart_labels': json.dumps(chart_labels),
        'chart_totals': json.dumps(chart_totals),
        'month_name': month_name,
        'selected_year': selected_year,
        }
    return render(request, 'tracker/transactions.html', context)

@login_required
def incomes(request):
    incomes = Income.objects.filter(owner=request.user).order_by('-id')
    total_income = Income.objects.filter(owner=request.user).aggregate(Sum('amount'))['amount__sum'] or 0
    context = {
        'incomes': incomes,
        'total_income': total_income,
    }
    return render(request, 'tracker/incomes.html', context)

@login_required
def transaction(request, transaction_id):
    transaction = Transaction.objects.get(id=transaction_id)
    context = {'transaction': transaction}
    return render(request, 'tracker/transaction.html', context)

@login_required
def add_transaction(request):
    if request.method != 'POST':
        # No data submitted; create a blank form
        form = TransactionForm()
    else:
        #POST data submitted; process data.
        form = TransactionForm(data=request.POST)
        if form.is_valid():
            new_transaction = form.save(commit=False)
            new_transaction.owner = request.user
            new_transaction.save()
            return redirect ('tracker:transactions')
        
    #Display a blank or invalid form
    context = {'form': form}
    return render(request, 'tracker/add_transaction.html', context)

@login_required
def delete_transaction(request, transaction_id):
    rm_transaction = get_object_or_404(Transaction, id = transaction_id)
    rm_transaction.delete()
    return redirect('tracker:transactions')

@login_required
def delete_income(request, income_id):
    rm_income = get_object_or_404(Income, id = income_id)
    rm_income.delete()
    return redirect('tracker:incomes')

@login_required
def add_income(request):
    if request.method != 'POST':
        form = IncomeForm()
    else:
        form = IncomeForm(data=request.POST)
        if form.is_valid():
            new_income = form.save(commit=False)
            new_income.owner = request.user
            new_income.save()
            return redirect('tracker:incomes')
    context = {'form': form}
    return render(request, 'tracker/add_income.html', context)

@login_required
def edit_transaction(request, transaction_id):
    transaction = Transaction.objects.get(id=transaction_id)

    if request.method != 'POST':
        form = TransactionForm(instance=transaction)
    else:
        form = TransactionForm(instance=transaction, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('tracker:transaction', transaction_id=transaction.id)
    context = {
            'form': form,
            'transaction': transaction,
            }
    return render(request, 'tracker/edit_transaction.html', context)

@login_required
def edit_income(request, income_id):
    income = Income.objects.get(id=income_id)

    if request.method != 'POST':
        form = IncomeForm(instance=income)
    else:
        form = IncomeForm(instance=income, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('tracker:incomes')
    context = {
            'form': form,
            'income': income,
            }
    return render(request, 'tracker/edit_income.html', context)


        
               
        
    

tracker/templates/tracker/add_income.html
{% extends 'tracker/base.html' %}

{% load django_bootstrap5 %}

{% block page_header %}
    <h2>Add New Income:</h2>
{% endblock page_header %}

{% block content %}
    {% if form.errors  %}
        <p>Invalid format.</p>
    {% endif %}
    <form action="{% url 'tracker:add_income' %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="Add Income" %}
    </form>

{% endblock content %}

tracker/templates/tracker/add_transaction.html
{% extends 'tracker/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
    <h2>Add New Transaction:</h2>
{% endblock page_header %}

{% block content %}
    {% if form.errors  %}
        <p>Invalid format.</p>
    {% endif %}
    <form action="{% url 'tracker:add_transaction' %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="Add Transaction" %}
    </form>
    
{% endblock content %}

tracker/templates/tracker/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Simple Budget</title>

    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'tracker:index' %}">Simple Budget</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarCollapse" aria-controls="navbarCollapse"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                    <a class="nav-link" href="{% url 'tracker:transactions' %}">Transactions</a></li>
                    <li class="nav-item">
                    <a class="nav-link" href="{% url 'tracker:incomes' %}">Incomes</a></li>
                </ul> <!-- End of links on left side of navbar -->
                <!-- Accont links-->
                <ul class="navbar-nav ms-auto mb-2 mb-md-0">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <span class="navbar-text me-2">
                                Hello, {{ user.username }}!
                            </span>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:login' %}">Log in</a>
                        </li>
                    {% endif %}
                </ul> <!-- End of accounts link -->
                {% if user.is_authenticated %}
                <form action="{% url 'accounts:logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-outline-secondary btn-sm">Log out</button>
                </form>
                {% endif %} 
            </div> <!-- Closes collapsible parts of navbar -->
        </div> <!-- Closes navbar's container -->
    </nav> <!-- End of navbar -->

    <main class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}
                
                    </div>
                </div>

            {% endblock page_header %}
        </div>
        <div>
            {% block content%}{% endblock content%}
        </div>
    </main>
</body>
</html>

tracker/templates/tracker/edit_income.html
{% extends "tracker/base.html" %}

{% block page_header %}
    <h2>Edit Income:</h2>
{% endblock page_header %}

{% block content %}
    <form action="{% url 'tracker:edit_income' income.id %}" method="post">
        {% csrf_token %}
        {{ form.as_div }}
        <button class="btn btn-primary" type="submit">Save changes</button>
    </form>
  
{% endblock content %}

tracker/templates/tracker/edit_transaction.html
{% extends "tracker/base.html" %}

{% block page_header %}
    <h2>Edit Transaction:</h2>
{% endblock page_header %}

{% block content %}
    <form action="{% url 'tracker:edit_transaction' transaction.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Save changes</button>
    </form>
{% endblock content %}

tracker/templates/tracker/incomes.html
{% extends 'tracker/base.html' %}

{% block page_header %}
    <h2>Incomes:</h2>
{% endblock page_header %}

{% block content %} 
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Source</th>
                <th scope="col">Amount</th>
            </tr>
        </thead>
        <tbody>
            {% for income in incomes %}
            <tr>
                <td>{{ income.source }}</td>
                <td>{{ income.amount }}</td>
                <td><a class="btn btn-primary" href="{% url 'tracker:edit_income' income.id %}">Edit</a></td>
                <td><a class="btn btn-danger" href="{% url 'tracker:delete_income' income.id %}">Delete</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="d-flex justify-content-center align-items-center">
        <a class="btn btn-success mb-4" href="{% url 'tracker:add_income' %}">Add Income</a>
    </div>
    <h2>Total Income: {{ total_income }}</h2>
    
{% endblock content %}
<!--
<p>Incomes:</p>
    <ul>
        {% for income in incomes %}
            <li>{{ income.source }} - {{ income.amount }}</li>
            <a href ='{% url 'tracker:edit_income' income.id %}'>Edit</a>
            <a href ="{% url 'tracker:delete_income' income.id %}">Delete</a>
        {% empty %}
            <li>No incomes added.</li>
        {% endfor %}
    </ul>
    <a href="{% url 'tracker:add_income' %}">Add Income</a>
    <h2>Total Income: {{ total_income }}</h2>
-->

tracker/templates/tracker/index.html
{% extends "tracker/base.html" %}

{% block page_header %}
    <div class="p-3 mb-4 bg-light border rounded-3">
        <div class="container-fluid py-4">
            <h1 class="display-3">Simple Budget</h1>
            <p class="lead">Managing your finances doesn’t have to be complicated. 
                                        With Simple Budget Tracker, you can gain full control over your money 
                                        and make informed decisions about your spending and saving.
            </p>

            {% if user.is_authenticated %}
                <a class="btn btn-primary btn-lg mt-1"
                    href="{% url 'tracker:transactions' %}">Transactions &raquo;
                </a>
            {% else %}
                <a class="btn btn-primary btn-lg mt-1"
                    href="{% url 'accounts:register' %}">Get started &raquo;
                </a>
            {% endif %}
        </div>
    </div>

{% endblock page_header %}

tracker/templates/tracker/transaction.html
{% extends 'tracker/base.html' %}

{% block page_header %}
    <h2>Transaction Details:</h2>
{% endblock page_header %}

{% block content%}
    {% if transaction %}
        <ul>
            <li>Date: {{ transaction.date }}</li>
            <li>Store: {{ transaction.store }}</li>
            <li>Amount: {{ transaction.amount }}</li>
            <li>Category: {{ transaction.get_category_display }}</li>
        </ul>
        <p><a class="btn btn-primary" href="{% url 'tracker:edit_transaction' transaction.id %}">Edit Transaction</a></p>
    {% else %}
        <p>Transaction not found.</p>
    {% endif %}
{% endblock content%}

tracker/templates/tracker/transactions.html
{% extends 'tracker/base.html' %}

{% block page_header %}
    <h2>Transactions:</h2>
{% endblock page_header %}


{% block content %}   
    
    <form method="GET" class="row row-cols-lg-auto g-3 align-items-center mb-4">
        {% for fields in filter.form %}
            <div class="col-12">
                {{ fields }}
            </div>
        {% endfor %}
        <div class="col-12">    
            <button type="submit" class="btn btn-primary">Filter</button>
        </div>            
    </form>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Date</th>
                <th scope="col">Store</th>
                <th scope="col">Amount</th>
                <th scope="col">Category</th>
            </tr>
        </thead>
        <tbody>
            {% for transaction in transactions %}
            <tr>
                <td>{{ transaction.date }}</td>
                <td>{{ transaction.store }}</td>
                <td>{{ transaction.amount }}</td>
                <td>{{ transaction.get_category_display }}</td>
                <td><a class="btn btn-primary" href="{% url 'tracker:transaction' transaction.id %}">View Details</a></td>
                <td><a class="btn btn-danger" href="{% url 'tracker:delete_transaction' transaction.id %}">Delete</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="d-flex gap-2 justify-content-center align-items-center">
        <a class="btn btn-success mb-4" href="{% url 'tracker:add_transaction' %}">Add transaction</a>
        
    </div>
    <h2>Total (all categories): {{ total_spent_all | floatformat:2 }}</h2>
    <hr>
    <h2>Total (filtered): {{ total_spent_filtered | floatformat:2 }}</h2>
    <hr>
    <h2>Balance: {{ balance | floatformat:2 }}</h2>

    <h3>
        Spending chart
        {% if month_name %}
        - {{ month_name }} {{ selected_year }}
        {% endif %} 
        
    </h3>

    <canvas id="spendingChart" width="400" height="200"></canvas>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <script>
        const ctx = document.getElementById('spendingChart').getContext('2d');
        const spendingChart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: {{ chart_labels|safe }},
                datasets: [{
                    label: 'Total Spent',
                    data: {{ chart_totals|safe }},
                    backgroundColor: 'rgba(255, 99, 132, 0.2)',
                    borderColor: 'rgba(255, 99, 132, 1)',
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });
    </script>
{% endblock content %}